first task
js-tasks-ru/jsbasic-20230928_julnbul pull request #1
Opened 2023-09-28 16:57 UTC by Julnbul

2023-09-28 16:57 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2023-09-29 02:46 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-09-29 02:51 UTC, koalex requested changes
Исправить замечание в **0-1**

2023-09-29 02:51 UTC, koalex commented on 0-module/1-task/index.js
> +  return s = m + n;
`s` не нужно (так эта `s` будет глобальной - это плохо)
просто `return m + n;`
либо объявить эту переменную `s` нужно, вот так:
```
let s = m + n;
return s;
```

2023-09-29 06:23 UTC, Julnbul commented on 0-module/1-task/index.js
> +  return s = m + n;
Исправила.

2023-09-29 14:09 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-09-29 14:11 UTC, koalex approved these changes

2023-09-29 14:11 UTC, merged